Fixing xargs 256 char limit for arguments: removing "-I"

diff --git a/bin/file-trailing-space b/bin/file-trailing-space
--- a/bin/file-trailing-space
+++ b/bin/file-trailing-space
@@ -28,22 +28,21 @@ DEFAULT_CUST_OPS=""
 
 # How to add your check here:
 # ---------------------------
-# %s   This comes from xargs and represents
+# $1   This comes from xargs and represents
 #      the current file to work on:
-#      xargs -I % sh '${MY_CHECK}'
+#      xargs sh '${MY_CHECK}' --
 #
 # __CUSTOM_OPT_PLACEHOLDER__
 #      This will be replaced either with custom options
 #      or with the default options.
 MY_REG="^.*[[:space:]]+$"
-MY_CHECK="grep --color=always -inHE \"${MY_REG}\" \"%\" || true"
+MY_CHECK="grep --color=always -inHE \"${MY_REG}\" \"\$1\" || true"
 
 # Can this check fix the problems?
 ENABLE_FIX=1
 
 # Command for fixing
-MY_FIX_CMD="sed -i\"\" \"s/[[:space:]]*\$//\" \"%\""
-
+MY_FIX_CMD="grep --color=always -iqE \"${MY_REG}\" \"\$1\" && (sed -i\"\" \"s/[[:space:]]*\$//\" \"%\" && echo \"Fixing: \$1\" || echo \"FAILED: \$1\") || true"
 
 # Command to be displayed for --info
 MY_INFO="grep -V | grep -E '([0-9]+\.+)+'"
@@ -60,8 +59,8 @@ MY_INFO="grep -V | grep -E '([0-9]+\.+)+'"
 #
 # Version
 #
-MY_VERSION="0.10"
-MY_DATE="2016-09-06"
+MY_VERSION="0.11"
+MY_DATE="2016-09-07"
 
 #
 # Credits
@@ -815,17 +814,17 @@ fi
 ### Text files (list-only)
 if [ "${MY_TXT}" = "1" ] && [ "${MY_LST}" = "1" ]; then
 	if [ "${MY_SHE}" != "" ]; then
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 -I % grep -Il '' '%' | tr '\n' '\0' | ${MY_SHE}"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 grep -Il '' | tr '\n' '\0' | ${MY_SHE}"
 	else
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 -I % grep -Il '' '%'"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 grep -Il ''"
 	fi
 
 ### Text files (run!!!)
 elif [ "${MY_TXT}" = "1" ] && [ "${MY_LST}" = "0" ]; then
 	if [ "${MY_SHE}" != "" ]; then
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 -I % grep -Il '' '%' | tr '\n' '\0' | ${MY_SHE} | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} -I % sh -c '${MY_CHECK}'"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 grep -Il '' | tr '\n' '\0' | ${MY_SHE} | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} sh -c '${MY_CHECK}' --"
 	else
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 -I % grep -Il '' '%' | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} -I % sh -c '${MY_CHECK}'"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 grep -Il '' | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} sh -c '${MY_CHECK}' --"
 	fi
 
 ### All files (list-only)
@@ -840,9 +839,9 @@ elif [ "${MY_TXT}" = "0" ] && [ "${MY_LST}" = "1" ]; then
 ### All files (run!!!)
 else
 	if [ "${MY_SHE}" != "" ]; then
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | ${MY_SHE} | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} -I % sh -c '${MY_CHECK}'"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | ${MY_SHE} | tr '\n' '\0' | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} sh -c '${MY_CHECK}' --"
 	else
-		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} -I % sh -c '${MY_CHECK}'"
+		MY_CMD="find ${MY_PATH} -type f ${NAME_PATTERN} ${EXCL_PATTERN} ${MY_SIZ} -print0 | xargs -0 -P ${CPU_CORES} -n1 ${XARGS_VERBOSE} sh -c '${MY_CHECK}' --"
 	fi
 
 fi
