Added requirements check

diff --git a/bin/inline-css b/bin/inline-css
--- a/bin/inline-css
+++ b/bin/inline-css
@@ -14,12 +14,19 @@ MY_DRY=0
 MY_LST=0
 MY_CFG=
 
+# Required binaries
+REQUIRED_BINS="sed grep find"
 
 # Regex to scan for inline CSS
 MY_REG="[[:space:]]+style[[:space:]]*="
 
 
 
+################################################################################
+#
+#  F U N C T I O N S
+#
+################################################################################
 
 print_usage() {
 
@@ -64,8 +71,42 @@ print_version() {
 	echo "email:  ${MY_EMAIL}"
 }
 
+check_requirements() {
+	_ret=0
+
+	# System binaries
+	for _bin in ${REQUIRED_BINS}; do
+		if ! command -v "${_bin}" >/dev/null 2>&1; then
+			echo "[ERR] Required sys binary '${_bin}' not found."
+			_ret=1
+		#else
+		#	echo "[OK]  Required sys binary '${_bin}' found."
+		fi
+	done
+
+	return ${_ret}
+}
 
 
+
+################################################################################
+#
+#  M A I N   E N T R Y   P O I N T
+#
+################################################################################
+
+
+#
+# Check requirements
+#
+if ! check_requirements; then
+	exit 1
+fi
+
+
+#
+# Read command line arguments
+#
 while [ $# -gt 0  ]; do
 	case "${1}" in
 
@@ -127,6 +168,7 @@ done
 #
 if [ "${MY_PATH}" = "" ]; then
 	echo "--path not specified"
+	echo "Type '${MY_NAME} --help' for available options."
 	exit 1
 fi
 
diff --git a/bin/inline-js b/bin/inline-js
--- a/bin/inline-js
+++ b/bin/inline-js
@@ -14,14 +14,21 @@ MY_DRY=0
 MY_LST=0
 MY_CFG=
 
+# Required binaries
+REQUIRED_BINS="sed grep find"
 
 # Regex to scan for inline JS
 MY_REG="[[:space:]]+on(abort|afterprint|beforeprint|beforeunload|blur|canplay|canplaythrough|change|click|contextmenu|copy|cuechange|cut|dblclick|drag|dragend|dragenter|dragleave|dragover|dragstart|drop|durationchange|emptied|ended|error|error|error|focus|hashchange|input|invalid|keydown|keypress|keyup|load|loadeddata|loadedmetadata|loadstart|message|mousedown|mousemove|mouseout|mouseover|mouseup|mousewheel|offline|online|pagehide|pageshow|paste|pause|play|playing|popstate|progress|ratechange|reset|resize|scroll|search|seeked|seeking|select|show|stalled|storage|submit|suspend|timeupdate|toggle|unload|volumechange|waiting|wheel)[[:space:]]*="
 
 
-DEFAULT_EXT="htm,html,php"
 
 
+
+################################################################################
+#
+#  F U N C T I O N S
+#
+################################################################################
 
 print_usage() {
 
@@ -66,8 +73,42 @@ print_version() {
 	echo "email:  ${MY_EMAIL}"
 }
 
+check_requirements() {
+	_ret=0
+
+	# System binaries
+	for _bin in ${REQUIRED_BINS}; do
+		if ! command -v "${_bin}" >/dev/null 2>&1; then
+			echo "[ERR] Required sys binary '${_bin}' not found."
+			_ret=1
+		#else
+		#	echo "[OK]  Required sys binary '${_bin}' found."
+		fi
+	done
+
+	return ${_ret}
+}
 
 
+
+################################################################################
+#
+#  M A I N   E N T R Y   P O I N T
+#
+################################################################################
+
+
+#
+# Check requirements
+#
+if ! check_requirements; then
+	exit 1
+fi
+
+
+#
+# Read command line arguments
+#
 while [ $# -gt 0  ]; do
 	case "${1}" in
 
@@ -129,6 +170,7 @@ done
 #
 if [ "${MY_PATH}" = "" ]; then
 	echo "--path not specified"
+	echo "Type '${MY_NAME} --help' for available options."
 	exit 1
 fi
 
@@ -187,10 +229,6 @@ elif [ "${MY_CFG}" != "" ] && [ "${MY_EXT}" = "" ]; then
 elif [ "${MY_CFG}" = "" ] && [ "${MY_EXT}" != "" ]; then
 	MY_EXT="${MY_EXT}"
 	echo "[ARG] Using cmd argument: ext: ${MY_EXT}"
-
-else
-	echo "[ARG] Using default value for ext: ${DEFAULT_EXT}"
-	MY_EXT="${DEFAULT_EXT}"
 fi
 
 
